application:
  library-path: C:\Neurotec_Biometric_13_0_SDK_2023-11-07\Bin\Biometric
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/new_infectious_disease_db
    username: postgres
    password: amos33
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: biometricApp
  threads:
    virtual:
      enabled: true
server:
  port: 7071
#intervention:
#  enabled: true
#  deduplication: true
#percentage: 0.8