package org.ecews.biometricapp.utils;

public final class DeDuplicationConfigs {
    public static final String DUPLICATE_CHECK = "DUPLICATE_CHECK";
    public static final String RECAPTURE_ONE_AND_BASELINE = "RECAPTURE_ONE_AND_BASELINE";
    public static final String RECAPTURE_TWO_AND_ONE = "RECAPTURE_TWO_AND_ONE";
    public static final String RECAPTURE_THREE_AND_TWO = "RECAPTURE_THREE_AND_TWO";
    public static final String RECAPTURE_ONE_DUPLICATE_CHECK = "RECAPTURE_ONE_DUPLICATE_CHECK";
    public static final String RECAPTURE_TWO_DUPLICATE_CHECK = "RECAPTURE_TWO_DUPLICATE_CHECK";
    public static final String RECAPTURE_THREE_DUPLICATE_CHECK = "RECAPTURE_THREE_DUPLICATE_CHECK";

    public static final String REPORT_LEVEL_SUMMARY = "REPORT_LEVEL_SUMMARY";
    public static final String REPORT_LEVEL_DETAIL = "REPORT_LEVEL_DETAIL";
    public static final String RECAPTURE_ONE_AND_BASELINE_REPORT = "RECAPTURE_ONE_AND_BASELINE_REPORT";
    public static final String RECAPTURE_ONE_DUPLICATE_CHECK_REPORT = "RECAPTURE_ONE_DUPLICATE_CHECK_REPORT";
    public static final String RECAPTURE_TWO_AND_ONE_REPORT = "RECAPTURE_TWO_AND_ONE_REPORT";
    public static final String RECAPTURE_THREE_AND_TWO_REPORT = "RECAPTURE_THREE_AND_TWO_REPORT";
    public static final String RECAPTURE_TWO_DUPLICATE_CHECK_REPORT = "RECAPTURE_TWO_DUPLICATE_CHECK_REPORT";
    public static final String RECAPTURE_THREE_DUPLICATE_CHECK_REPORT = "RECAPTURE_THREE_DUPLICATE_CHECK_REPORT";
}
